name: Deploy to GH Pages upon push to `master`
on:
  push:
    branches:
    - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        #      --------------
      - name: Install packages
        run: npm ci
#        #      --------------
      - name: Build
        run: npm run build
#        #      --------------
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        #      --------------
#      - name: Deploy to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: build # The folder the action should deploy.
#      --------------
      - name: List files in the repository
        run: |
         ls ${{ github.workspace }}
